### PR TITLE
Book world branch2

### PR DESCRIPTION
**Pull request by RanimHilal**
Hello, I would like to ask you to put  a href="#name">name</a>" in the places where we are supposed to put a link so it can be easier for us to add the links.

### CODE REVIEW

**Comment by AfraAljarwan** [comment]
Hi, This is good idea and it will be much easier for us.

**Comment by AfraAljarwan** [comment]
but how you want us to write it?

**Comment by RanimHilal** [comment]
> but how you want us to write it?

any text you have to link it with other members websites use what I wrote. I edited it just put a tag before the "a" because it didn't show.

**Comment by AfraAljarwan** [comment]
okay

**Comment by Shamsa900** [comment]
Yes, I agree

I will also share mine as soon I edit it all

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Shamsa900** [comment]
About Us-


Hello everyone I want to share with you my About Us Page to discuss
my idea for this page is to make the text empty as you can see but when the mouse comes over  the text the text will get filled by the color black . I want to represent the idea of how reading fill us with knowledge and joy, also there is a red bookmark on the left  side of the page and it will be a link to go back to the homepage as you click on it 

I want it to be simple because I want the user to focuses mainly on the idea of the website.

as you can see it's only the text and the bookmark because I will continues the rest of the text style and page on the next phase using css.


The html code:


`<!DOCTYPE html>

<html lang="en">
<head>
<meta charset = "utf-8">
<title>About Us</title>
</head>

<body>
<hr>
<a href="https://www.google.com/">
  Bookmark</a>

<h1>About Us:</h1>
<h2>Greeting from BookWorld !</h2>
<br>

<h4>who are BookWorld ?</h4>
<br>
<h4>The website that will take you  in a journey through various books in a way that you would enjoy even scrolling
 through it not just you will also will have the chance to interact and much more.</h4>

<h4>our website focuses on letting readers interact and find books that suit their taste in
 a new different way, by categorizing books in groups not depending on their genre
 and adding features that our users will surely enjoy.</h4>
 <br>

<h4>Our Purpose</h4>
<br>
<h4>As a person who likes to read, we need features that will let 
us have fun when reading and deciding what to read. For example,
sharing books and their information with others and more. 
So, our website doesn’t provide the book but help people enjoy reading in an interesting way.</h4>
<br>

<h4>Our Vision</h4>
<br>
<h4>is to provide you with the best experience of how to enjoy your time reading and sharing your favorites because what matter
is to have quality time doing what you really enjoy.</h4>
</body>
</html>`

**Comment by fatmalshamsi** [comment]
thanks raneem that will be efficient.

**Comment by Hajar-Abdullah** [comment]
Yes Ranimm that will be a great and useful idea.

**Pull request closed without merging**
