### PR TITLE
Book world branch2

### PR DESCRIPTION
**Pull request by Hajar-Abdullah**
Hello
Did anyone have an idea how can I make something like " Scroll Up and down button " in html?

RatingPage-Hajar drawio

### CODE REVIEW

**Comment by Shamsa900** [comment]
yes in the next phase this will be possible

**Comment by Hajar-Abdullah** [comment]
OK then I will wait until the next phase.

**Comment by AfraAljarwan** [comment]
yes doing the scroll up and down button in next phase would be better because they are introduced in CSS.

**Comment by Hajar-Abdullah** [comment]
Ok then, I will wait until the next phase. 
Thank you all.

**Pull request closed without merging**
