### PR TITLE
Book world branch2

### PR DESCRIPTION
**Pull request by fatmalshamsi**
hello guys regarding using images I want to know how to upload it as a link here so I can use it in my code.

### CODE REVIEW

**Comment by RanimHilal** [comment]
hello, what you need to do is put your code in the same file as the images and in your code just put the image name.png/jpg.... depends on your image type.

**Comment by RanimHilal** [comment]
about the images what is the size all of you used?

**Comment by AfraAljarwan** [comment]
Hi, I used 
height=100 width=70

**Comment by fatmalshamsi** [comment]
im using width = 50, height = 50 for the lists book icon

**Comment by AfraAljarwan** [comment]
fatma when you will save the image do not leave space while writing the name to avoid getting error

**Comment by Hajar-Abdullah** [comment]
I'm using width =60, height = 80.

**Comment by Shamsa900** [comment]
I'm using width="100" height="50"

**Pull request closed without merging**
